replicaCount: 1

image:
  repository: gcr.io/google-samples/gb-frontend
  tag: v5
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: NodePort        # expose service outside cluster (use minikube service)
  port: 80
  nodePort: 30080       # fixed port, so you know where to access

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - guestbook.local
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
